domain: yunha-sohn.xyz
url: https://yunha-sohn.xyz
baseurl:
title: Yun Ha Sohn
subtitle: 
author: Yun Ha Sohn
simple_search: http://google.com/search
description: 
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: Asia/Seoul
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/mistralk.github.com/
